[server]
bind_ip = "0.0.0.0"
bind_port = 9000
cookie_secret = "medbookCookie"
# google apps domain
auth_domain = ""

[domains]
  [domains.example1]
  host = "su2c-dev.ucsc.edu:9000"
  upstream = [ "su2c-dev.ucsc.edu:8081"]
  client_id = "210653342985.apps.googleusercontent.com"
  client_secret = "tRD12MAYeFxVZOYkgqKK8AoP"

